# This is a basic workflow to help you get started with Actions

name: Sample Book App Workflow

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/build

  deploy-dev:
    runs-on: self-hosted
    needs: [build]
    steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/deploy
          with:
            env: "DEV"
            port: "1010"

  test-dev:
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
        - uses: actions/checkout@v4
          with:
            repository: 'istyaheru/api-automation'
            
        - uses: ./.github/actions/test
          with:
            env: DEV
            test-suite: BOOKS

  deploy-stg:
    runs-on: self-hosted
    needs: [test-dev]
    steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/deploy
          with:
            env: "STG"
            port: "2020"

  test-stg:
    runs-on: self-hosted
    needs: [deploy-stg]
    steps:
        - uses: ./.github/actions/test
          with:
            env: STG
            test-suite: BOOKS

  deploy-prd:
    runs-on: self-hosted
    needs: [test-stg]
    steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/deploy
          with:
            env: "PRD"
            port: "3030"

  test-prd:
    runs-on: self-hosted
    needs: [deploy-prd]
    steps:
        - uses: ./.github/actions/test
          with:
            env: PRD
            test-suite: BOOKS
