# This is a basic workflow to help you get started with Actions

name: Sample Book App Workflow

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Big steppy
          run: echo "Building of node application started"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
        - uses: actions/checkout@v4
        - name: Big steppy
          run: echo "Deployment to DEV started"

  test-dev:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    steps:
        - uses: actions/checkout@v4
        - name: Big steppy
          run: echo "Testing on DEV started"

  deploy-stg:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
        - uses: actions/checkout@v4
        - name: Big steppy
          run: echo "Deployment to STG started"

  test-stg:
    runs-on: ubuntu-latest
    needs: [deploy-stg]
    steps:
        - uses: actions/checkout@v4
        - name: Big steppy
          run: echo "Testing on STG started"

  deploy-prd:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
        - uses: actions/checkout@v4
        - name: Big steppy
          run: echo "Deployment to PRD started"

  test-prd:
    runs-on: ubuntu-latest
    needs: [deploy-prd]
    steps:
        - uses: actions/checkout@v4
        - name: Big steppy
          run: echo "Testing on PRD started"
